name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  avoid-redundant-workflows:
    name: Avoid redundant workflows
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1

  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run lint with standard
        run: npx standard --fix